### ISSUE TITLE
Automatisation de la mise en production de l'application

### ISSUE THREAD

**Issue by bynicodevelop** [bynicodevelop/atrap.io-beta#16]
Permettre l'automatisation de l'application sur le hosting de firebase.

Gestion des fichiers de configuration pour l'environnement.

3 types de fichier : 

* Développement
* Staging
* Production

**Comment by bynicodevelop** [comment]
Article intéressant sur le génération de variables d'environnement avec Travis : https://brettdewoody.com/secure-environment-variables-with-travis/

**Comment by bynicodevelop** [comment]
## Firebase configuration

```
npm install -g firebase-tools
firebase login
firebase init
```

## Travis configuration 

firebase login:ci

```
docker run -it --rm ruby:latest bash
gem install travis
travis encrypt "1/firebase_CI_token" -r githubusername/reponame
```

**Comment by bynicodevelop** [comment]
Pour ajouter des variables d'environnement directement avec travis et dans le fichier de configuration : 

`travis encrypt BINTRAY_USER=user --add env.global`

**Comment by bynicodevelop** [comment]
Possibilité de créer une fichier .env.travis et le copier de la façon suivante : 

```
before_script:
    - cp .env.travis .env
```

**Comment by bynicodevelop** [comment]
Pour la création du fichier : 

`- echo MY_VARIABLE = $MY_VARIABLE > .env`

**Comment by bynicodevelop** [comment]
Solution retenue : Github action

* permet de façon logique la séparation des fichiers (actions)
* Intégration à firebase prise en compte

Exemple probable de configuration : 

```
name: Firebase Continous Deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - run: npm install
      - run: npm run generate
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_HOSTING }}
          FIREBASE_PROJECT: PROJECTID
```
