### ISSUE TITLE
Mise en place d'un reverse proxy

### ISSUE THREAD

**Issue by bynicodevelop** [bynicodevelop/atrap.io-beta#28]
Pour l'intégration de sonarqube (#26) ainsi que d'autres solutions créer un serveur avec son reverse proxy.

Utilisation de traefik pour la mise en place.

Exemple de fichier docker-composer.yml : 

```
version: '3'

services:
          reverse-proxy:
           image: traefik:v2.2
           command:
             - "--api.insecure"
             - "--providers.docker"
             - "--entryPoints.web.address=:80"
           ports:
             - "80:80"
             - "8080:8080"
           volumes:
             - /var/run/docker.sock:/var/run/docker.sock

          whoami:
           image: "containous/whoami"
           labels:
             - "traefik.enable=true"
             - "traefik.http.routers.whoami.rule=Host(`DOMAIN`)"
             - "traefik.http.routers.whoami.entrypoints=web"

          whoami2:
           image: "containous/whoami"
           labels:
             - "traefik.enable=true"
             - "traefik.http.routers.whoami2.rule=Host(`DOMAIN`)"
             - "traefik.http.routers.whoami2.entrypoints=web"
             - "traefik.http.routers.whoami2.middlewares=auth"
             - "traefik.http.middlewares.auth.basicauth.users=user:$$apr1$$q8eZFHjF$$Fvmkk//V6Btlaf2i/ju5n/"
```
